name: React Native CI (pnpm)

on:
  push:
    branches: [ "develop" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run mobile lint
        run: pnpm --filter hyoit-rn lint

      - name: Run check-in tests
        run: pnpm --filter hyoit-rn test:check-in
